backend config handling

diff --git a/clouduct-tf b/clouduct-tf
--- a/clouduct-tf
+++ b/clouduct-tf
@@ -6,11 +6,13 @@ set -e
 ALL_PHASES="network storage compute build"
 ALL_ENVS="dev test int prod"
 
+DEFAULT_ENVIRONMENT=dev
+
 # --------------------------------------------------------------------------------------------------
 # PREPARE
 # --------------------------------------------------------------------------------------------------
 
-TWRAP_CONFIG_FILE=".twrap"
+TWRAP_CONFIG_FILE=".clouduct-tf"
 
 # ensure we're executing in the correct directory
 SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
@@ -26,14 +28,14 @@ else
   exit 1
 fi
 
-if [[ -z $CLOUDUCT_PROJECTNAME ]]; then
-  echo "missing environment variable CLOUDUCT_PROJECTNAME"
+if [[ -z $TF_VAR_project_name ]]; then
+  echo "missing environment variable TF_VAR_project_name"
   echo "should have been set in $TWRAP_CONFIG_FILE"
   exit 1
 fi
 
-if [[ -z $CLOUDUCT_REGION ]]; then
-  echo "missing environment variable CLOUDUCT_REGION"
+if [[ -z $TF_VAR_region ]]; then
+  echo "missing environment variable TF_VAR_region"
   echo "should have been set in $TWRAP_CONFIG_FILE"
   exit 1
 fi
@@ -73,8 +75,10 @@ ALL_PHASES_TEST="+($ALL_PHASES_ALT)"
 ALL_ENVS_TEST="+($ALL_ENVS_ALT)"
 
 if contains "$1" "$ALL_ENVS" ; then
-  ENVIRONMENT="$1"
+  TF_VAR_environment="$1"
   shift
+elif [[ -z $TF_VAR_environment ]]; then
+  TF_VAR_environment="$DEFAULT_ENVIRONMENT"
 fi
 
 while contains "$1" "$ALL_PHASES"; do
@@ -92,7 +96,7 @@ if [[ "$1" == "--help" ]]; then
   exit 0
 fi
 
-if [[ $# -gt 0 ]]; then 
+if [[ $# -gt 0 ]]; then
   echo "unknown parameter(s) $*"
   echo
   usage
@@ -116,40 +120,33 @@ fi
 
 PHASES_IN_EXEC_ORDER=$(trim $PHASES_IN_EXEC_ORDER)
 
-echo "$CLOUDUCT_PROJECTNAME env: ($ENVIRONMENT) phases: ($PHASES_IN_EXEC_ORDER) command: ($terraform_command)"
+echo "$TF_VAR_project_name env: ($TF_VAR_environment) phases: ($PHASES_IN_EXEC_ORDER) command: ($terraform_command)"
 
-# ensure if the NAME-infra directory exists:
-INFRA_DIR="${CLOUDUCT_PROJECTNAME}-infra"
-if [ ! -d "${INFRA_DIR}" ]; then
-  echo "could not find directory ${INFRA_DIR}"
-  exit 2
-fi
+# # ensure if the NAME-infra directory exists:
+# INFRA_DIR="${CLOUDUCT_PROJECTNAME}-infra"
+# if [ ! -d "${INFRA_DIR}" ]; then
+#   echo "could not find directory ${INFRA_DIR}"
+#   exit 2
+# fi
+
+INFRA_DIR="$( cd "$( dirname "$0" )" && pwd )"
 
 # --------------------------------------------------------------------------------------------------
 # EXECUTE
 # --------------------------------------------------------------------------------------------------
 
-# TODO INTERMEDIATE_DIR="terrorform"
-
 for phase in ${PHASES_IN_EXEC_ORDER}; do
-  echo "${INFRA_DIR}/$phase"
+  # echo "${INFRA_DIR}/$phase"
   pushd "${INFRA_DIR}/$phase" > /dev/null
 
-  # terraform get
-  TODO: init immer aufrufen
-  TODO -reconfigure
+  BUCKET="${TF_VAR_project_name}-infra-${TF_VAR_environment}-remote-state-bucket"
 
-  # if [[ "${terraform_command}" ==  'bootstrap' ]]; then
-  #   terraform init \
-  #       -backend-config "project_name=${CLOUDUCT_PROJECTNAME}" \
-  #       -backend-config "environment=${ENVIRONMENT}" \
-  #       -backend-config "region=${region}"
-  # else
-  #   terraform "${terraform_command}" \
-  #       -var "project_name=${CLOUDUCT_PROJECTNAME}" \
-  #       -var "environment=${environment}" \
-  #       -var "region=${region}"
-  # fi
+  terraform init -reconfigure \
+    -backend-config="region=${TF_VAR_region}" \
+    -backend-config="bucket=${BUCKET}" \
+    -backend-config="key=${phase}"
+
+  terraform "${terraform_command}"
 
   popd > /dev/null
 
